version: '3.8'

services:
  mysql_base:                    
    container_name: mysql_base   
    image: mysql:8.0.40         
    restart: always

    ports:
      - 3315:3306              

    env_file:
      - ./.env.credenciais     
    
    volumes:
      - mysql_data:/var/lib/mysql 

volumes:
  mysql_data:                   
    driver: local


