version: '3.8'

services:
  mysql_base:                    
    container_name: mysql_base   
    image: mysql:8.0.40         
    restart: always

    ports:
      - 3316:3306              

    env_file:
      - ./.env.credenciais     
    
    volumes:
      - mysql_data:/var/lib/mysql 
    networks:
      - app-network

  api:
    container_name: nestjs_api
    build:
      context: ../ 
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql_base
    networks:
      - app-network
    env_file:
      - ./.env.credenciais

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:                   
    driver: local